name: Daily Palm Oil Alert

on:
  schedule:
    - cron: "0 1 * * *"  # UTC time = 9AM PH time
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Palm Oil Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python get_palm_price.py
