name: Daily Palm Oil Alert

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 09:00 AM GMT+8
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Script
        run: python get_palm_price.py
